---
title: "burdened genes PPI partner extraction"
output: html_notebook
date: "`r format(Sys.time(), '%d %B, %Y')`"
---

## load packages

```{r, message=FALSE, warning=FALSE}
library(openxlsx)
library(biomaRt)
library(clusterProfiler)
library(org.Hs.eg.db)
library(tidyverse)
library(magrittr)
```

## load data

```{r}
## significant gene import

burdengenes_dementia_list=read.csv("./metadata/list_burdengenes_dementia.csv")
burdengenes_AD_list=read.csv("./metadata/list_burdengenes_AD.csv")
burdengenes_ADearly_list=read.csv("./metadata/list_burdengenes_ADearly.csv")

## BIOGRID PPI data import

human_BIOGRID_PPI <- read.csv("./data/BIOGRID-ALL-4.2.192_human.tab.csv")
```

## ID transformation

```{r}
human_BIOGRID_PPI.ENTREZID_A <- bitr(human_BIOGRID_PPI$OFFICIAL_SYMBOL_A, fromType = "SYMBOL",
                                           toType = c("ENTREZID"), 
                                           OrgDb = org.Hs.eg.db)

human_BIOGRID_PPI.ENTREZID_B <- bitr(human_BIOGRID_PPI$OFFICIAL_SYMBOL_B, fromType = "SYMBOL",
                                     toType = c("ENTREZID"), 
                                     OrgDb = org.Hs.eg.db)

human_BIOGRID_PPI$ENTREZID_A <- apply(human_BIOGRID_PPI,1,function(x){if(x[3] %in% human_BIOGRID_PPI.ENTREZID_A$SYMBOL){human_BIOGRID_PPI.ENTREZID_A[which(human_BIOGRID_PPI.ENTREZID_A$SYMBOL==x[3]),"ENTREZID"]}else{"NA"}})
human_BIOGRID_PPI$ENTREZID_B <- apply(human_BIOGRID_PPI,1,function(x){if(x[4] %in% human_BIOGRID_PPI.ENTREZID_B$SYMBOL){human_BIOGRID_PPI.ENTREZID_B[which(human_BIOGRID_PPI.ENTREZID_B$SYMBOL==x[4]),"ENTREZID"]}else{"NA"}})
human_BIOGRID_PPI$ENTREZID_A <- unlist(as.character(human_BIOGRID_PPI$ENTREZID_A))
human_BIOGRID_PPI$ENTREZID_B <- unlist(as.character(human_BIOGRID_PPI$ENTREZID_B))
human_BIOGRID_PPI <- human_BIOGRID_PPI[order(human_BIOGRID_PPI$ENTREZID_A),]

write.csv(human_BIOGRID_PPI,"./metadata/BIOGRID-ALL-4.2.192_human.tab_final.csv",row.names = FALSE)

burdengenes_dementia_list$ENTREZID <- as.character(burdengenes_dementia_list$ENTREZID)
burdengenes_AD_list$ENTREZID <- as.character(burdengenes_AD_list$ENTREZID)
burdengenes_ADearly_list$ENTREZID <- as.character(burdengenes_ADearly_list$ENTREZID)
```

## PPI interaction genes extraction

```{r}
AD_PPI_partners=unlist(apply(burdengenes_AD_list,1,function(x){if(x[3] %in% human_BIOGRID_PPI$ENTREZID_A){human_BIOGRID_PPI[which(human_BIOGRID_PPI$ENTREZID_A==x[3]),"ENTREZID_B"]}else{"NA"}}))
AD_PPI_partners=c(AD_PPI_partners,unlist(apply(burdengenes_AD_list,1,function(x){if(x[3] %in% human_BIOGRID_PPI$ENTREZID_B){human_BIOGRID_PPI[which(human_BIOGRID_PPI$ENTREZID_B==x[3]),"ENTREZID_A"]}else{"NA"}})))
AD_PPI_partners=unique(AD_PPI_partners)
AD_PPI_partners=na.omit(AD_PPI_partners)
AD_PPI_partners=AD_PPI_partners[which(AD_PPI_partners!="NA")]

dementia_PPI_partners=unlist(apply(burdengenes_dementia_list,1,function(x){if(x[3] %in% human_BIOGRID_PPI$ENTREZID_A){human_BIOGRID_PPI[which(human_BIOGRID_PPI$ENTREZID_A==x[3]),"ENTREZID_B"]}else{"NA"}}))
dementia_PPI_partners=c(dementia_PPI_partners,unlist(apply(burdengenes_dementia_list,1,function(x){if(x[3] %in% human_BIOGRID_PPI$ENTREZID_B){human_BIOGRID_PPI[which(human_BIOGRID_PPI$ENTREZID_B==x[3]),"ENTREZID_A"]}else{"NA"}})))
dementia_PPI_partners=unique(dementia_PPI_partners)
dementia_PPI_partners=na.omit(dementia_PPI_partners)
dementia_PPI_partners=dementia_PPI_partners[which(dementia_PPI_partners!="NA")]

ADearly_PPI_partners=unlist(apply(burdengenes_ADearly_list,1,function(x){if(x[3] %in% human_BIOGRID_PPI$ENTREZID_A){human_BIOGRID_PPI[which(human_BIOGRID_PPI$ENTREZID_A==x[3]),"ENTREZID_B"]}else{"NA"}}))
ADearly_PPI_partners=c(ADearly_PPI_partners,unlist(apply(burdengenes_ADearly_list,1,function(x){if(x[3] %in% human_BIOGRID_PPI$ENTREZID_B){human_BIOGRID_PPI[which(human_BIOGRID_PPI$ENTREZID_B==x[3]),"ENTREZID_A"]}else{"NA"}})))
ADearly_PPI_partners=unique(ADearly_PPI_partners)
ADearly_PPI_partners=na.omit(ADearly_PPI_partners)
ADearly_PPI_partners=ADearly_PPI_partners[which(ADearly_PPI_partners!="NA")]

AD_PPI_cluster=c(AD_PPI_partners,burdengenes_AD_list$ENTREZID)
dementia_PPI_cluster=c(dementia_PPI_partners,burdengenes_dementia_list$ENTREZID)
ADearly_PPI_cluster=c(ADearly_PPI_partners,burdengenes_ADearly_list$ENTREZID)

AD_PPI_cluster=unique(AD_PPI_cluster)
dementia_PPI_cluster=unique(dementia_PPI_cluster)
ADearly_PPI_cluster=unique(ADearly_PPI_cluster)
```

## output geneset results

```{r}
write.table(dementia_PPI_cluster,"./metadata/dementia_PPI_cluster.txt",sep = '\t',row.names = FALSE,col.names = FALSE,quote = FALSE)
write.table(dementia_PPI_partners,"./metadata/dementia_PPI_partners.txt",sep = '\t',row.names = FALSE,col.names = FALSE,quote = FALSE)
write.table(AD_PPI_cluster,"./metadata/AD_PPI_cluster.txt",sep = '\t',row.names = FALSE,col.names = FALSE,quote = FALSE)
write.table(AD_PPI_partners,"./metadata/AD_PPI_partners.txt",sep = '\t',row.names = FALSE,col.names = FALSE,quote = FALSE)
write.table(ADearly_PPI_cluster,"./metadata/ADearly_PPI_cluster.txt",sep = '\t',row.names = FALSE,col.names = FALSE,quote = FALSE)
write.table(ADearly_PPI_partners,"./metadata/ADearly_PPI_partners.txt",sep = '\t',row.names = FALSE,col.names = FALSE,quote = FALSE)
```

## network data preparation

```{r}
AD_PPI_net=data.frame()
tmp=data.frame()
for(i in 1:length(burdengenes_AD_list$ENTREZID)){
  if(burdengenes_AD_list[i,"ENTREZID"] %in% human_BIOGRID_PPI$ENTREZID_A){
    tmp=human_BIOGRID_PPI[which(human_BIOGRID_PPI$ENTREZID_A==burdengenes_AD_list[i,"ENTREZID"]),]
  }
  else{tmp=data.frame()}
  AD_PPI_net=rbind(AD_PPI_net,tmp)
  
  if(burdengenes_AD_list[i,"ENTREZID"] %in% human_BIOGRID_PPI$ENTREZID_B){
    tmp=human_BIOGRID_PPI[which(human_BIOGRID_PPI$ENTREZID_B==burdengenes_AD_list[i,"ENTREZID"]),]
  }
  else{tmp=data.frame()}
  AD_PPI_net=rbind(AD_PPI_net,tmp)
}

dementia_PPI_net=data.frame()
tmp=data.frame()
for(i in 1:length(burdengenes_dementia_list$ENTREZID)){
  if(burdengenes_dementia_list[i,"ENTREZID"] %in% human_BIOGRID_PPI$ENTREZID_A){
    tmp=human_BIOGRID_PPI[which(human_BIOGRID_PPI$ENTREZID_A==burdengenes_dementia_list[i,"ENTREZID"]),]
  }
  else{tmp=data.frame()}
  dementia_PPI_net=rbind(dementia_PPI_net,tmp)
  
  if(burdengenes_dementia_list[i,"ENTREZID"] %in% human_BIOGRID_PPI$ENTREZID_B){
    tmp=human_BIOGRID_PPI[which(human_BIOGRID_PPI$ENTREZID_B==burdengenes_dementia_list[i,"ENTREZID"]),]
  }
  else{tmp=data.frame()}
  dementia_PPI_net=rbind(dementia_PPI_net,tmp)
}

ADearly_PPI_net=data.frame()
tmp=data.frame()
for(i in 1:length(burdengenes_ADearly_list$ENTREZID)){
  if(burdengenes_ADearly_list[i,"ENTREZID"] %in% human_BIOGRID_PPI$ENTREZID_A){
    tmp=human_BIOGRID_PPI[which(human_BIOGRID_PPI$ENTREZID_A==burdengenes_ADearly_list[i,"ENTREZID"]),]
  }
  else{tmp=data.frame()}
  ADearly_PPI_net=rbind(ADearly_PPI_net,tmp)
  
  if(burdengenes_ADearly_list[i,"ENTREZID"] %in% human_BIOGRID_PPI$ENTREZID_B){
    tmp=human_BIOGRID_PPI[which(human_BIOGRID_PPI$ENTREZID_B==burdengenes_ADearly_list[i,"ENTREZID"]),]
  }
  else{tmp=data.frame()}
  ADearly_PPI_net=rbind(ADearly_PPI_net,tmp)
}
```

## network data output

```{r}
net_list<-list()
net_list$dementia_PPI <- dementia_PPI_net
net_list$AD_PPI <- AD_PPI_net
net_list$ADearly_PPI <- ADearly_PPI_net
write.xlsx(net_list,"./metadata/net_allsets_BIOGRID_PPI.xlsx")
```

## filter PPI pairs overlapped with AD known genes

```{r, message=FALSE, warning=FALSE}
AD_known_genes<-read.table("./metadata/AD_knownsig_geneset_v2.txt")[,1]

overlap_net.dementia_PPI<-dementia_PPI_net[which((dementia_PPI_net$ENTREZID_A %in% AD_known_genes)|(dementia_PPI_net$ENTREZID_B %in% AD_known_genes)),] %>% group_by(OFFICIAL_SYMBOL_A,OFFICIAL_SYMBOL_B,ENTREZID_A,ENTREZID_B) %>% summarise() %>% as.data.frame
overlap_net.AD_PPI<-AD_PPI_net[which((AD_PPI_net$ENTREZID_A %in% AD_known_genes)|(AD_PPI_net$ENTREZID_B %in% AD_known_genes)),] %>% group_by(OFFICIAL_SYMBOL_A,OFFICIAL_SYMBOL_B,ENTREZID_A,ENTREZID_B) %>% summarise() %>% as.data.frame
overlap_net.EOAD_PPI<-ADearly_PPI_net[which((ADearly_PPI_net$ENTREZID_A %in% AD_known_genes)|(ADearly_PPI_net$ENTREZID_B %in% AD_known_genes)),] %>% group_by(OFFICIAL_SYMBOL_A,OFFICIAL_SYMBOL_B,ENTREZID_A,ENTREZID_B) %>% summarise() %>% as.data.frame

overlap.list<-list()
overlap.list$all_burdened_genes<-burdengenes_dementia_list
overlap.list$dementia<-overlap_net.dementia_PPI
overlap.list$AD<-overlap_net.AD_PPI
overlap.list$EOAD<-overlap_net.EOAD_PPI

write.xlsx(overlap.list,"./metadata/burdened-genes_overlapped_PPI-pairs_with_ADknown-genes_all.xlsx")
```

## add evidence to the ranking list

```{r}
# first script for extracting the evidence list

evidence_df<-read.table("./metadata/list_TRAPD_caseonly_mutatedgenes_an_burdengenes.txt",header = T)
caseonly_mutated_genes<-read.table("./metadata/list_TRAPD_caseonly_dementia_entrezid.txt")[,1]

evidence_df$burdened_genes<-evidence_df$ENTREZID %>% lapply(.,function(x){if(x %in% burdengenes_dementia_list$ENTREZID){1}else{0}}) %>% unlist
evidence_df$burdened_AD<-evidence_df$ENTREZID %>% lapply(.,function(x){if(x %in% burdengenes_AD_list$ENTREZID){1}else{0}}) %>% unlist
evidence_df$burdened_EOAD<-evidence_df$ENTREZID %>% lapply(.,function(x){if(x %in% burdengenes_ADearly_list$ENTREZID){1}else{0}}) %>% unlist
evidence_df$caseonly_mutated<-evidence_df$ENTREZID %>% lapply(.,function(x){if(x %in% caseonly_mutated_genes){1}else{0}}) %>% unlist
evidence_df %<>% arrange(desc(caseonly_mutated)) %>% arrange(desc(burdened_genes))
evidence_df$PPI_overlap_with_ADknowngenes<-evidence_df$ENTREZID %>% lapply(.,function(x){if(x %in% c(overlap_net.dementia_PPI$ENTREZID_A,overlap_net.dementia_PPI$ENTREZID_B)){1}else{0}}) %>% unlist

write.xlsx(evidence_df,"./metadata/evidence-ranking_table_all-case-only-and-burdened-genes.xlsx")

# the next script is "enrichment in LOF intolerant genes"
```

## save.image

```{r}
save(AD_PPI_cluster,AD_PPI_partners,dementia_PPI_partners,dementia_PPI_cluster,ADearly_PPI_cluster,ADearly_PPI_partners,file = "./burdengenes_PPIpartner_extraction_genesets.RData")
rm(human_BIOGRID_PPI,i,tmp,human_BIOGRID_PPI.ENTREZID_A,human_BIOGRID_PPI.ENTREZID_B,net_list)
save.image("./burdengenes_PPIpartner_extraction.RData")
```
